{% set name = "mgzip" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mgzip-{{ version }}.tar.gz
  sha256: c2585a8c6b66ec65c2a0ccbb13236cd60782b6a150ca7fd54fb6814825126876

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - mgzip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vinlyx/mgzip
  summary: A multi-threading implementation of Python gzip module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
