{% set name = "mgzip" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mgzip-{{ version }}.tar.gz
  sha256: c3acc22203e571f83e5764923ea534c0a9638b938ff6a4b4687a575fd0f2f15c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - mgzip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/vinlyx/mgzip
  summary: A multi-threading implementation of Python gzip module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
